# Generated by Django 4.2.1 on 2023-05-09 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_rename_doctor_appointment_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
